# Generated by Django 3.2 on 2023-01-06 12:05

from django.db import migrations

def init_services_insurance(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Insurance = apps.get_model('services', 'Insurance')
    Insurance.objects.create(
        content=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_services_insurance),
    ]
