# Generated by Django 3.2 on 2023-01-09 11:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_init_empty_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(default='store/images/default.png', upload_to='store/images')),
            ],
        ),
    ]
