# Generated by Django 3.2 on 2023-01-06 12:05

from django.db import migrations

def init_services_customergratitude(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CustomerGratitude = apps.get_model('services', 'CustomerGratitude')
    CustomerGratitude.objects.create(
        content=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_customergratitude'),
    ]

    operations = [
        migrations.RunPython(init_services_customergratitude),
    ]
