# Generated by Django 3.2 on 2023-03-08 08:00

from django.db import migrations


def init_register_new(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    News = apps.get_model('services', 'News')
    News.objects.create(
        title="title",
        descripton="descripton"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230308_1458'),
    ]

    operations = [
        migrations.RunPython(init_register_new),
    ]
