# Generated by Django 3.2 on 2023-03-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_init_register_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
