# Generated by Django 3.2 on 2023-01-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230108_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='corlors',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
