# Generated by Django 3.2 on 2023-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230108_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='corlors',
            field=models.ManyToManyField(related_name='product', to='product.Corlor'),
        ),
    ]
