# Generated by Django 3.2 on 2023-02-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_corlors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='corlors',
        ),
    ]
