# Generated by Django 3.2 on 2023-02-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20230205_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('color', 'product')},
        ),
    ]
