# Generated by Django 3.2 on 2023-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productcolor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlassesMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlassesShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('color', 'product')},
        ),
        migrations.AddField(
            model_name='product',
            name='form_face',
            field=models.ManyToManyField(related_name='product_form_face', to='product.FormFace'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(related_name='product_gender', to='product.Gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='glasses_material',
            field=models.ManyToManyField(related_name='product_glasses_material', to='product.GlassesMaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='glasses_shape',
            field=models.ManyToManyField(related_name='product_glasses_shape', to='product.GlassesShape'),
        ),
    ]
