# Generated by Django 3.2 on 2023-02-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_best_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
