# Generated by Django 3.2 on 2023-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230213_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='formface',
            name='image',
            field=models.ImageField(default='store/images/default.png', upload_to='form_face/images'),
        ),
        migrations.AddField(
            model_name='gender',
            name='image',
            field=models.ImageField(default='store/images/default.png', upload_to='gender/images'),
        ),
        migrations.AddField(
            model_name='glassesmaterial',
            name='image',
            field=models.ImageField(default='store/images/default.png', upload_to='glasses_material/images'),
        ),
        migrations.AddField(
            model_name='glassesshape',
            name='image',
            field=models.ImageField(default='store/images/default.png', upload_to='glasses_shape/images'),
        ),
    ]
