# Generated by Django 3.2 on 2023-02-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20230213_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='formface',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gender'),
        ),
    ]
