# Generated by Django 3.2 on 2023-02-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_formface_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='corlors',
            new_name='colors',
        ),
    ]
