# Generated by Django 3.2 on 2023-02-18 07:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_corlors_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='corlor',
            name='code',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
