# Generated by Django 3.2 on 2023-02-27 15:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_corlor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[640, 480], upload_to='blog/%Y/%m/%d')),
                ('author_display', models.CharField(max_length=255)),
                ('date_display', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('preview_body', models.CharField(max_length=511)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
