# Generated by Django 3.2 on 2023-03-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_display',
        ),
    ]
