# Generated by Django 3.2 on 2023-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='origin_price',
        ),
    ]
