# Generated by Django 3.2 on 2023-01-06 12:05

from django.db import migrations

def init_config_contact(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Contact = apps.get_model('config', 'Contact')
    Contact.objects.create(
        nameshop = " ",
        address = " ",
        Phone = " ",
        facebook = " ",
        shopee_id = " ",
        lazada_ip = " "
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_config_contact),
    ]
