# Generated by Django 3.2 on 2023-02-26 05:41

from django.db import migrations

def init_config_email(apps, schema_editor):
    # We can't import the EmailConfig model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    email_config = apps.get_model('config', 'EmailConfig')
    email_config.objects.create(
        email="pempem16146024@gmail.com",
        app_password="vufetvmnbexlvcxp"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_emailconfig'),
    ]

    operations = [
        migrations.RunPython(init_config_email),
    ]
