# Generated by Django 3.2 on 2023-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_init_email_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
    ]
