# Generated by Django 3.2 on 2023-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainback_ground', models.ImageField(default='store/images/default.png', upload_to='store/images')),
                ('inform_backgroud', models.ImageField(default='store/images/default.png', upload_to='store/images')),
                ('promotion_background', models.ImageField(default='store/images/default.png', upload_to='store/images')),
            ],
        ),
    ]
