# Generated by Django 3.2 on 2023-02-28 14:22

from django.db import migrations


def init_config_image_management(apps, schema_editor):
    # We can't import the ImageManagement model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    image_management = apps.get_model('config', 'ImageManagement')
    image_management.objects.create(
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_imagemanagement'),
    ]

    operations = [
        migrations.RunPython(init_config_image_management),
    ]
