# Generated by Django 3.2 on 2023-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_init_image_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_warantee', models.CharField(max_length=1024)),
                ('free_eye_exam', models.CharField(max_length=1024)),
                ('old_collection_renewed', models.CharField(max_length=1024)),
                ('clean_and_maintain_your_glasses', models.CharField(max_length=1024)),
            ],
        ),
    ]
