# Generated by Django 3.2 on 2023-03-01 15:12

from django.db import migrations


def init_config_insurance_config(apps, schema_editor):
    # We can't import the InsuranceConfig model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    insurance_config = apps.get_model('config', 'InsuranceConfig')
    insurance_config.objects.create(
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_insuranceconfig'),
    ]

    operations = [
        migrations.RunPython(init_config_insurance_config),
    ]
