# Generated by Django 3.2 on 2023-03-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_init_insurance_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceconfig',
            old_name='clean_and_maintain_your_glasses',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='insuranceconfig',
            old_name='free_eye_exam',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='insuranceconfig',
            name='old_collection_renewed',
        ),
        migrations.RemoveField(
            model_name='insuranceconfig',
            name='policy_warantee',
        ),
    ]
