# Generated by Django 3.2 on 2023-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_init_3_insurance_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemanagement',
            name='bestseller_background',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
    ]
