# Generated by Django 3.2 on 2023-03-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_imagemanagement_bestseller_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='store/images/default.png', upload_to='store/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemanagement',
            name='mainback_ground',
        ),
        migrations.AddField(
            model_name='imagemanagement',
            name='main_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.mainbackgroundimage'),
        ),
    ]
