# Generated by Django 3.2 on 2023-03-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20230308_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemanagement',
            name='main_background',
        ),
        migrations.AddField(
            model_name='mainbackgroundimage',
            name='image_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_management', to='config.imagemanagement'),
        ),
    ]
