# Generated by Django 3.2 on 2023-03-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20230308_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='google_map_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
