# Generated by Django 3.2 on 2023-03-08 17:00

from django.db import migrations


def init_config_promotion_register(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    config_promotion_register = apps.get_model('config', 'ConfigPromotionRegister')
    config_promotion_register.objects.create(
        title="title",
        descripton="descripton"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_configpromotionregister'),
    ]

    operations = [
        migrations.RunPython(init_config_promotion_register),
    ]
