# Generated by Django 3.2 on 2023-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_init_config_promotion_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemanagement',
            name='formface_recommend_glass_image',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
        migrations.AddField(
            model_name='imagemanagement',
            name='gender_recommend_glass_image',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
        migrations.AddField(
            model_name='imagemanagement',
            name='glasses_material_recommend_glass_image',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
        migrations.AddField(
            model_name='imagemanagement',
            name='glasses_shape_recommend_glass_image',
            field=models.ImageField(default='store/images/default.png', upload_to='store/images'),
        ),
    ]
