# Generated by Django 3.2 on 2023-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_auto_20230313_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReceiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
