# Generated by Django 3.2 on 2023-03-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_emailreceiveorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemanagement',
            old_name='formface_recommend_glass_image',
            new_name='recommend_glass_image',
        ),
        migrations.RemoveField(
            model_name='imagemanagement',
            name='gender_recommend_glass_image',
        ),
        migrations.RemoveField(
            model_name='imagemanagement',
            name='glasses_material_recommend_glass_image',
        ),
        migrations.RemoveField(
            model_name='imagemanagement',
            name='glasses_shape_recommend_glass_image',
        ),
    ]
