# Generated by Django 3.2 on 2023-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_auto_20230319_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recommend_glass_description',
            field=models.TextField(default=''),
        ),
    ]
