# Generated by Django 3.2 on 2023-03-30 03:23

from django.db import migrations, models

def init_config_font(apps, schema_editor):
    # We can't import the FontConfig model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    font_config = apps.get_model('config', 'FontConfig')
    font_config.objects.create()

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_contact_recommend_glass_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Tahoma', 'Tahoma'), ('Trebuchet MS', 'Trebuchet MS'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Garamond', 'Garamond'), ('Courier New', 'Courier New'), ('Brush Script MT', 'Brush Script MT')], default='Arial', max_length=20)),
            ],
        ),
        migrations.RunPython(init_config_font),
    ]
