# Generated by Django 3.2 on 2023-03-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
