name: CI

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  deploy_if_merged:
    if: github.event.pull_request.merged == true
    name: deploy
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.PASSWORD }}
        with:
          source: "."
          target: "/var/www/mywebsite"

      - name: Deploy to VPS via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD_LOGIN_SSH }}
          port: 22
          command_timeout: 200m
          script: |
            cd /var/www/mywebsite
            docker-compose stop
            docker-compose rm -f
            docker rmi -f $(docker images --filter "dangling=true" -q --no-trunc)
            docker-compose build --no-cache
            docker-compose up -d
